### ISSUE TITLE
[FEAT] 회원 정보 API - 백엔드

### ISSUE THREAD

**Issue by proysm** [CSID-DGU/2024-1-CECD4-TheRed-4#6]
# TO-DO

- [x] API 응답
- [x] 회원 정보 조회
- [x] 닉네임 중복 체크
- [x] 회원 정보 수정
